---------------------------Usuarios Globales---------------------
--admin global--
GRANT RELOAD, SHUTDOWN, PROCESS, REFERENCES, SHOW DATABASES, SUPER, LOCK TABLES, REPLICATION SLAVE, REPLICATION CLIENT, CREATE USER ON *.* TO `admin_global`@`%` IDENTIFIED BY PASSWORD '*BD874F60E5DC49673E3CB10AB040055B44FBDAD9' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `sakila`.* TO `admin_global`@`%`;
--admin data--
GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO `admin_data`@`%` IDENTIFIED BY PASSWORD '*BD874F60E5DC49673E3CB10AB040055B44FBDAD9';

---------------------------Usuarios Sakila-----------------------
--sakila_master--
GRANT USAGE ON *.* TO `sakila_master`@`%` IDENTIFIED BY PASSWORD '*BD874F60E5DC49673E3CB10AB040055B44FBDAD9';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `sakila`.* TO `sakila_master`@`%`;
--sakila_query--
GRANT USAGE ON *.* TO `sakila_query`@`%` IDENTIFIED BY PASSWORD '*BD874F60E5DC49673E3CB10AB040055B44FBDAD9';

GRANT SELECT ON `sakila`.* TO `sakila_query`@`%`;

---------------------------Usuarios Examen------------------------
-- admin_examen  Password: Admin123 --
GRANT USAGE ON *.* TO `admin_exam`@`%` IDENTIFIED BY PASSWORD '*B37ACB9927C1F3B520BBF976386EAB76A08F3367';

GRANT SELECT, INSERT, UPDATE ON `sakila`.* TO `admin_exam`@`%`;

-- guess_examen --
GRANT USAGE ON *.* TO `guess_examen`@`%` IDENTIFIED BY PASSWORD '*E27FCC422509DA3131FEA64587995EEEEA0C221F';

GRANT SELECT ON `sakila`.* TO `guess_examen`@`%`;